import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Coins, Copy, Gift, KeyRound, Megaphone, Users, Wallet } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { pageTitle } from "@/lib/brand";
import { apiRequest, type AppUser } from "@/lib/api";
import { useAppAuth } from "@/lib/auth";
import { useCurrency } from "@/lib/currency";
import { levelBenefits, milestoneRewards } from "@/lib/rewards-system";

type DashboardResponse = { user: AppUser; stats: { totalInvestment: number; totalRiseCoins: number; walletBalance: number; availableBalance: number; totalCommissionEarned: number; totalRewardValue: number; accountType: string }; referralSummary: { level1: number; level2: number; level3: number }; announcements: Array<{ id: string; title: string; message: string }>; recentTransactions: Array<{ id: string; amount: number; direction: "credit" | "debit"; description: string; createdAt: string }> };
export const Route = createFileRoute("/_app/dashboard")({ head: () => ({ meta: [{ title: pageTitle("Dashboard") }] }), component: Dashboard });

function Dashboard() {
  const { token, user } = useAppAuth(); const { format } = useCurrency(); const [data, setData] = useState<DashboardResponse | null>(null); const [feed, setFeed] = useState<Array<{ id: string; type: string; name: string }>>([]);
  useEffect(() => { if (!token) return; const load = () => void apiRequest<DashboardResponse>("/user/dashboard", { token }).then(setData).catch(() => null); load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [token]);
  useEffect(() => { void apiRequest<{ items: typeof feed }>("/public/activity-feed").then((r) => setFeed(r.items ?? [])).catch(() => null); }, []);
  const d = data?.stats; const member = data?.user ?? user; const coins = d?.totalRiseCoins ?? 0; const next = levelBenefits.find((l) => l.riseCoinsRequired > coins) ?? levelBenefits.at(-1)!; const progress = Math.min(100, coins / next.riseCoinsRequired * 100); const teams = data?.referralSummary; const totalTeam = (teams?.level1 ?? 0) + (teams?.level2 ?? 0) + (teams?.level3 ?? 0); const initials = (member?.name ?? "NX").split(" ").map((p) => p[0]).join("").slice(0, 2).toUpperCase(); const ticker = useMemo(() => ["Welcome to your NexoRise workspace", ...feed.slice(0, 5).map((x) => `${x.name} joined the network`)], [feed]);
  const copyCode = async () => { if (!member?.referralCode) return; await navigator.clipboard.writeText(member.referralCode); toast.success("Referral code copied"); };
  const stats = [["Total Investment", format(d?.totalInvestment ?? 0), Wallet, "text-primary"], ["Total Rise Coins", coins.toLocaleString(), Coins, "text-success"], ["Available Balance", format(d?.availableBalance ?? 0), Gift, "text-gold"], ["Wallet Balance", format(d?.walletBalance ?? 0), Wallet, "text-secondary"]] as const;
  return <div className="mx-auto w-full max-w-6xl space-y-4 pb-8">
    <div className="overflow-hidden rounded-full border border-border/50 bg-card/80 px-4 py-2 text-xs text-muted-foreground"><div className="flex w-max gap-12 animate-marquee">{[...ticker, ...ticker].map((x, i) => <span key={i}>✦ {x}</span>)}</div></div>
    <section className="dashboard-panel flex flex-col gap-5 p-5 sm:p-7 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><div className="grid size-16 shrink-0 place-items-center rounded-full border-2 border-primary bg-primary/10 text-xl font-bold text-primary sm:size-20">{initials}</div><div><p className="eyebrow">Welcome back</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{member?.name ?? "Nexo member"}</h1><p className="mt-1 text-sm text-muted-foreground">{member?.email}</p><span className="mt-2 inline-flex rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{(d?.accountType ?? "investor").replace("_", " ")}</span></div></div><div><p className="eyebrow">Referral code</p><div className="mt-2 flex items-center gap-2"><span className="rounded-lg bg-muted px-3 py-2 font-mono font-semibold">{member?.referralCode ?? "—"}</span><button onClick={copyCode} className="rounded-lg bg-primary p-2 text-primary-foreground" aria-label="Copy referral code"><Copy className="size-4" /></button></div></div></section>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label, value, Icon, tint]) => <div className="dashboard-panel p-4 sm:p-5" key={label}><div className="flex items-center justify-between"><p className="eyebrow">{label}</p><div className={`rounded-xl bg-muted p-2 ${tint}`}><Icon className="size-4" /></div></div><p className="mt-3 text-xl font-bold sm:text-2xl">{value}</p><div className="mt-4 h-1.5 rounded-full bg-muted"><div className="h-full w-2/3 rounded-full bg-primary" /></div></div>)}</div>
    <div className="grid gap-4 md:grid-cols-3">{[["Total team members", totalTeam, Users], ["Direct team", teams?.level1 ?? 0, Users], ["Referral income", format(d?.totalCommissionEarned ?? 0), Coins]].map(([label, value, Icon]) => <div className="dashboard-panel p-5" key={String(label)}><div className="flex items-center gap-2 text-sm text-muted-foreground"><Icon className="size-4 text-primary" />{label}</div><p className="mt-3 text-2xl font-bold">{value}</p></div>)}</div>
    <section className="dashboard-panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="section-title"><Coins className="size-5 text-primary" /> Rise Coins progress</h2><p className="mt-1 text-sm text-muted-foreground">Your current rank and next reward target.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">{next.name}</span></div><div className="mt-5 flex items-end justify-between text-sm"><span><strong className="text-xl">{coins.toLocaleString()}</strong> Rise Coins</span><span className="text-muted-foreground">{next.riseCoinsRequired.toLocaleString()} target</span></div><div className="mt-2 h-3 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div></section>
    <section className="dashboard-panel p-5 sm:p-6"><h2 className="section-title"><Gift className="size-5 text-primary" /> Reward plan</h2><p className="mt-1 text-sm text-muted-foreground">Milestones from your existing rewards program.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b border-border text-xs uppercase text-muted-foreground"><tr><th className="py-3">Level</th><th>Rise Coins</th><th>Reward</th><th>Status</th></tr></thead><tbody>{milestoneRewards.map((reward) => { const req = levelBenefits.find((l) => l.level === reward.level)?.riseCoinsRequired ?? 0; const earned = coins >= req; return <tr key={reward.level} className="border-b border-border/60 last:border-0"><td className="py-3 font-semibold">{reward.level}</td><td>{req.toLocaleString()}</td><td>{format(reward.amount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${earned ? "bg-success/10 text-success" : "bg-muted text-muted-foreground"}`}>{earned ? "Unlocked" : "Locked"}</span></td></tr>; })}</tbody></table></div></section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="dashboard-panel p-5"><h2 className="section-title"><Wallet className="size-5 text-primary" /> Recent wallet activity</h2><div className="mt-4 space-y-2">{(data?.recentTransactions ?? []).slice(0, 4).map((tx) => <div className="flex items-center justify-between rounded-xl bg-muted/60 p-3" key={tx.id}><div><p className="text-sm font-semibold">{tx.description}</p><p className="text-xs text-muted-foreground">{new Date(tx.createdAt).toLocaleDateString("en-PK")}</p></div><span className={tx.direction === "credit" ? "font-bold text-success" : "font-bold text-destructive"}>{tx.direction === "credit" ? "+" : "-"}{format(tx.amount)}</span></div>)}{!data?.recentTransactions?.length && <p className="text-sm text-muted-foreground">No recent activity yet.</p>}</div></section><section className="dashboard-panel p-5"><h2 className="section-title"><Megaphone className="size-5 text-primary" /> Announcements</h2><div className="mt-4 space-y-3">{(data?.announcements ?? []).slice(0, 3).map((a) => <div key={a.id}><p className="font-semibold">{a.title}</p><p className="mt-1 text-sm text-muted-foreground">{a.message}</p></div>)}{!data?.announcements?.length && <p className="text-sm text-muted-foreground">No announcements right now.</p>}</div></section></div>
    <section className="dashboard-panel flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="section-title"><KeyRound className="size-5 text-primary" /> Grow your network</h2><p className="mt-1 text-sm text-muted-foreground">Share your referral link and track your team from Referrals.</p></div><Link to="/referrals" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Open referrals <ArrowUpRight className="size-4" /></Link></section>
  </div>;
}
