import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, ShieldCheck, ShoppingBag, Target, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BrandLockup } from "@/components/BrandLockup";
import { BRAND_NAME, pageTitle } from "@/lib/brand";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: pageTitle("Home") }] }), component: HomePage });

const features = [
  { icon: Users, title: "Networking", text: "Build meaningful connections and grow with a supportive community." },
  { icon: BookOpen, title: "Learn & Grow", text: "Develop practical skills and confidence for your future." },
  { icon: ShieldCheck, title: "Trust & Transparency", text: "Clear platform rules and straightforward member information." },
  { icon: Target, title: "Ranks & Rewards", text: "Progress through achievement-based ranks and rewards." },
];

function HomePage() {
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-40 border-b border-border/60 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link to="/"><BrandLockup titleClassName="text-lg font-bold" subtitleClassName="tracking-[0.2em]" /></Link><nav className="hidden items-center gap-6 text-sm font-medium text-muted-foreground md:flex"><a href="#about" className="hover:text-primary">About Us</a><a href="#services" className="hover:text-primary">Services</a><Link to="/courses" className="hover:text-primary">Training</Link><Link to="/rewards" className="hover:text-primary">Ranks & Rewards</Link></nav><div className="flex items-center gap-2"><Link to="/login"><Button variant="ghost">Login</Button></Link><Link to="/login"><Button className="gradient-primary text-primary-foreground">Get Started</Button></Link></div></div></header>
    <main>
      <section className="gradient-hero"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.05fr,0.95fr] lg:px-10 lg:py-24"><div><span className="inline-flex rounded-full border border-primary/20 bg-background/70 px-4 py-2 text-xs font-semibold text-primary">Learn • Grow • Lead</span><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[0.98] tracking-tight sm:text-6xl lg:text-7xl">Build yourself with <span className="text-gradient-gold">{BRAND_NAME}</span>.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Learn, improve your skills, strengthen your leadership, and explore modern business opportunities in a supportive community.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login"><Button size="lg" className="gradient-primary text-primary-foreground">How it works <ArrowRight className="ml-2 size-4" /></Button></Link><Link to="/login"><Button size="lg" variant="outline">Login</Button></Link></div></div><div className="relative"><div className="absolute inset-10 rounded-full bg-primary/20 blur-3xl" /><div className="relative rounded-[2rem] border border-primary/20 bg-background/80 p-8 shadow-2xl"><div className="grid aspect-square place-items-center rounded-[1.5rem] bg-gradient-to-br from-primary/20 via-background to-secondary/30"><BrandLockup imageClassName="size-24 rounded-3xl" titleClassName="text-3xl font-black" subtitleClassName="tracking-[0.3em]" /></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-muted p-3"><b className="block text-lg text-primary">Learn</b>Skills</div><div className="rounded-xl bg-muted p-3"><b className="block text-lg text-primary">Grow</b>Confidence</div><div className="rounded-xl bg-muted p-3"><b className="block text-lg text-primary">Lead</b>Teams</div></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 lg:px-10"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text }) => <div className="dashboard-panel p-5" key={title}><Icon className="mb-4 size-7 text-primary" /><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>
      <section id="about" className="mx-auto max-w-5xl scroll-mt-24 px-5 py-12 text-center lg:px-10"><p className="eyebrow">About Us</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Welcome to {BRAND_NAME} 🚀</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{BRAND_NAME} is a growth-focused platform dedicated to helping individuals develop practical skills, build confidence, strengthen leadership abilities, and explore modern business opportunities.</p><p className="mx-auto mt-4 max-w-3xl leading-7 text-muted-foreground">We believe that true growth comes through learning, consistency, teamwork, and continuous self-development. Our aim is to create an environment where individuals can improve their professional abilities and move forward with confidence.</p><div className="mt-10 grid gap-4 text-left md:grid-cols-3"><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">🎯 Our Mission</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">To empower individuals with practical knowledge, professional skills, leadership development, and growth opportunities.</p></div><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">👁️ Our Vision</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">To build a strong community of skilled, confident, responsible, and ambitious individuals.</p></div><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">💎 Core Values</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Integrity • Learning • Teamwork • Consistency • Leadership</p></div></div></section>
      <section id="services" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-10"><div className="text-center"><p className="eyebrow">What we offer</p><h2 className="mt-3 text-4xl font-black tracking-tight">Opportunities to learn and grow</h2></div><div className="mt-8 grid gap-5 md:grid-cols-3"><Link to="/courses" className="dashboard-panel p-6 transition-transform hover:-translate-y-1"><BookOpen className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Training & Courses</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Access structured learning and practical skill development.</p></Link><Link to="/plans" className="dashboard-panel p-6 transition-transform hover:-translate-y-1"><ShoppingBag className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Business Opportunities</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Explore the plans and opportunities available in your account.</p></Link><Link to="/rewards" className="dashboard-panel p-6 transition-transform hover:-translate-y-1"><Target className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Ranks & Rewards</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Track progress and discover the rewards connected to achievement.</p></Link></div></section>
      <section className="mx-5 mb-16 rounded-3xl bg-foreground px-6 py-12 text-center text-background lg:mx-auto lg:max-w-7xl"><h2 className="text-3xl font-black sm:text-4xl">Your journey starts now.</h2><p className="mx-auto mt-3 max-w-xl text-background/70">Learn, grow, and move forward with NexoRise.</p><Link to="/login" className="mt-6 inline-flex"><Button className="bg-primary text-primary-foreground hover:bg-primary/90">Join {BRAND_NAME} <ArrowRight className="ml-2 size-4" /></Button></Link></section>
    </main><footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">© {new Date().getFullYear()} {BRAND_NAME}. Learn • Earn • Grow.</footer>
  </div>;
}
