import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Crown, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BrandLockup } from "@/components/BrandLockup";
import { BRAND_NAME, pageTitle } from "@/lib/brand";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: pageTitle("Home") }] }), component: HomePage });
const departments = [{ title: "Business Development", items: ["Business Development", "Business Growth", "Member/Customer Communication", "Opportunity Development", "Business Support", "Team/Business Expansion"] }, { title: "Leadership & Training", items: ["Leadership Development", "Beginner Training", "Trainer Sessions", "Member Guidance", "Team Development", "Skills Development", "Personal Growth"] }, { title: "E-Commerce", items: ["E-Commerce Activities", "Online Selling", "Product/Service Management", "Customer Handling", "E-Commerce Development", "Online Business Growth"] }];
const courses = ["Network Marketing Fundamentals", " Sales & Closing Mastery", " Leadership & Team Building", "- Communication Skills", " Lead Generation", " Social Media Marketing", " Personal Branding", " Public Speaking & Presentation", " Customer Follow-Up Skills", " Digital Marketing Basics"];

function HomePage() { return <div className="min-h-screen bg-background"><header className="sticky top-0 z-40 border-b border-border/60 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link to="/"><BrandLockup titleClassName="text-lg font-bold" /></Link><nav className="hidden gap-6 text-sm font-semibold text-muted-foreground md:flex"><a href="#about">About Us</a><a href="#departments">Departments</a><a href="#courses">Training</a><a href="#contact">Contact Us</a></nav><Link to="/login"><Button className="gradient-primary text-primary-foreground">Login</Button></Link></div></header><main>
<section className="gradient-hero"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-2 lg:px-10 lg:py-24"><div><span className="inline-flex rounded-full border border-primary/20 bg-background/70 px-4 py-2 text-xs font-bold text-primary">LEARN  GROW  LEAD</span><h1 className="mt-6 text-5xl font-black leading-none tracking-tight sm:text-6xl">Build yourself with <span className="text-gradient-gold">{BRAND_NAME}</span>.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Develop practical skills, build confidence, strengthen leadership abilities, and explore modern business opportunities.</p><div className="mt-8 flex gap-3"><Link to="/login"><Button size="lg" className="gradient-primary text-primary-foreground">Start your journey <ArrowRight className="ml-2 size-4" /></Button></Link><a href="#courses"><Button size="lg" variant="outline">Explore training</Button></a></div></div><div className="dashboard-panel p-5 sm:p-7"><div className="rounded-3xl bg-gradient-to-br from-primary/15 via-background to-secondary/25 p-6"><p className="eyebrow">Your growth journey</p><h2 className="mt-2 text-2xl font-black">Make progress that matters.</h2><div className="mt-6 rounded-2xl bg-background p-4 shadow-sm"><div className="flex justify-between text-sm font-bold"><span>Rise Coins progress</span><span className="text-primary">Growing</span></div><div className="mt-3 h-3 rounded-full bg-muted"><div className="h-full w-3/5 rounded-full bg-primary" /></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-background p-4"><BookOpen className="size-5 text-primary" /><p className="mt-3 font-bold">Learn skills</p></div><div className="rounded-2xl bg-background p-4"><Users className="size-5 text-primary" /><p className="mt-3 font-bold">Build a team</p></div></div></div></div></div></section>
<section id="about" className="mx-auto max-w-5xl scroll-mt-24 px-5 py-16 text-center lg:px-10"><p className="eyebrow">About Us</p><h2 className="mt-3 text-4xl font-black">Welcome to {BRAND_NAME} </h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{BRAND_NAME} is a growth-focused platform dedicated to helping individuals develop practical skills, build confidence, strengthen leadership abilities, and explore modern business opportunities.</p><p className="mx-auto mt-4 max-w-3xl leading-7 text-muted-foreground">We believe that true growth comes through learning, consistency, teamwork, and continuous self-development.</p><div className="mt-8 grid gap-4 text-left md:grid-cols-3">{[[" Our Mission", "Empower individuals with practical knowledge, professional skills, leadership development, and growth opportunities."], [" Our Vision", "Build a strong community of skilled, confident, responsible, and ambitious individuals."], [" Core Values", "Integrity  Learning  Teamwork  Consistency  Leadership"]].map(([title, text]) => <div className="dashboard-panel p-5" key={title}><h3 className="font-bold text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>
<section id="departments" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-10"><div className="text-center"><p className="eyebrow">Working Departments</p><h2 className="mt-3 text-4xl font-black">Support for every stage of growth</h2></div><div className="mt-8 grid gap-5 md:grid-cols-3">{departments.map((d) => <div className="dashboard-panel p-6" key={d.title}><h3 className="text-xl font-bold text-primary">{d.title}</h3><ul className="mt-4 space-y-2 text-sm text-muted-foreground">{d.items.map((item) => <li key={item}> {item}</li>)}</ul></div>)}</div></section>
<section id="courses" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-10"><div className="text-center"><p className="eyebrow">Explore Training</p><h2 className="mt-3 text-4xl font-black">Build practical skills</h2></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{courses.map((course) => <div className="dashboard-panel p-4" key={course}><BookOpen className="mb-3 size-5 text-primary" /><h3 className="font-semibold">{course}</h3><p className="mt-1 text-xs text-muted-foreground">Practical guidance to help you learn and grow.</p></div>)}</div><div className="mt-8 text-center"><Link to="/login"><Button className="gradient-primary text-primary-foreground">Confirm your seat <ArrowRight className="ml-2 size-4" /></Button></Link></div></section>
<section id="contact" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-10"><div className="dashboard-panel p-6"><div className="text-center"><p className="eyebrow">Contact Us</p><h2 className="mt-3 text-3xl font-black">Need help? Contact Admin</h2></div><div className="mx-auto mt-6 grid max-w-4xl gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Phone 1", "03057410110"], ["Phone 2", "03290263136"], ["Email", "nexorise333@gmail.com"], ["Location", "Sargodha"]].map(([label, value]) => <div className="rounded-xl bg-muted p-4" key={label}><p className="eyebrow">{label}</p><p className="mt-2 break-all font-semibold">{value}</p></div>)}</div></div></section>
<section className="mx-5 mb-16 rounded-3xl bg-foreground px-6 py-12 text-center text-background lg:mx-auto lg:max-w-7xl"><Crown className="mx-auto size-8 text-primary" /><h2 className="mt-3 text-3xl font-black">Your journey starts now.</h2><Link to="/login" className="mt-6 inline-flex"><Button className="bg-primary text-primary-foreground">Get started <ArrowRight className="ml-2 size-4" /></Button></Link></section></main><footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">Copyright {new Date().getFullYear()} {BRAND_NAME}. Learn  Earn  Grow.</footer></div>; }






