import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, CheckCircle2, Crown, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BrandLockup } from "@/components/BrandLockup";
import { BRAND_NAME, pageTitle } from "@/lib/brand";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: pageTitle("Home") }] }), component: HomePage });

function HomePage() {
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-40 border-b border-border/60 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link to="/"><BrandLockup titleClassName="text-lg font-bold" /></Link><nav className="hidden gap-6 text-sm font-semibold text-muted-foreground md:flex"><a href="#about">About Us</a><a href="#services">Services</a><Link to="/courses">Training</Link><Link to="/rewards">Ranks & Rewards</Link></nav><Link to="/login"><Button className="gradient-primary text-primary-foreground">Login</Button></Link></div></header>
    <section className="gradient-hero"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 lg:grid-cols-2 lg:px-10 lg:py-20"><div><span className="inline-flex rounded-full border border-primary/20 bg-background/70 px-4 py-2 text-xs font-bold text-primary">LEARN • GROW • LEAD</span><h1 className="mt-6 text-5xl font-black leading-none tracking-tight sm:text-6xl lg:text-7xl">Build yourself with <span className="text-gradient-gold">{BRAND_NAME}</span>.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Develop practical skills, build confidence, strengthen leadership abilities, and explore modern business opportunities.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login"><Button size="lg" className="gradient-primary text-primary-foreground">Start your journey <ArrowRight className="ml-2 size-4" /></Button></Link><Link to="/courses"><Button size="lg" variant="outline">Explore training</Button></Link></div></div>
      <div className="relative"><div className="absolute inset-8 rounded-full bg-primary/20 blur-3xl" /><div className="relative rounded-[2rem] border border-primary/20 bg-background/85 p-5 shadow-2xl sm:p-7"><div className="rounded-[1.5rem] bg-gradient-to-br from-primary/15 via-background to-secondary/25 p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">Member progress</p><h2 className="mt-2 text-2xl font-black">Your next level starts here</h2></div><div className="grid size-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><Crown className="size-6" /></div></div><div className="mt-7 rounded-2xl bg-background p-4 shadow-sm"><div className="flex justify-between text-sm font-bold"><span>Rise Coins</span><span className="text-primary">Progress</span></div><div className="mt-3 h-3 rounded-full bg-muted"><div className="h-full w-3/5 rounded-full bg-primary" /></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Keep learning and growing</span><span>Next rank</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-background p-4 shadow-sm"><BookOpen className="size-5 text-primary" /><p className="mt-3 font-bold">Learn skills</p><p className="mt-1 text-xs text-muted-foreground">Practical training</p></div><div className="rounded-2xl bg-background p-4 shadow-sm"><Users className="size-5 text-primary" /><p className="mt-3 font-bold">Build a team</p><p className="mt-1 text-xs text-muted-foreground">Grow together</p></div></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-muted p-3"><CheckCircle2 className="mx-auto mb-1 size-4 text-primary" />Learn</div><div className="rounded-xl bg-muted p-3"><CheckCircle2 className="mx-auto mb-1 size-4 text-primary" />Grow</div><div className="rounded-xl bg-muted p-3"><CheckCircle2 className="mx-auto mb-1 size-4 text-primary" />Lead</div></div></div></div></div></section>
    <section id="about" className="mx-auto max-w-5xl scroll-mt-24 px-5 py-16 text-center lg:px-10"><p className="eyebrow">About Us</p><h2 className="mt-3 text-4xl font-black">Welcome to {BRAND_NAME} 🚀</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{BRAND_NAME} is a growth-focused platform dedicated to helping individuals develop practical skills, build confidence, strengthen leadership abilities, and explore modern business opportunities.</p><div className="mt-8 grid gap-4 text-left md:grid-cols-3"><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">🎯 Our Mission</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Empowering individuals with practical knowledge, professional skills, leadership development, and growth opportunities.</p></div><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">👁️ Our Vision</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Building a strong community of skilled, confident, responsible, and ambitious individuals.</p></div><div className="dashboard-panel p-5"><h3 className="font-bold text-primary">💎 Core Values</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Integrity • Learning • Teamwork • Consistency • Leadership</p></div></div></section>
    <section id="services" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-10"><h2 className="text-center text-4xl font-black">Learn, grow, and move forward</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><Link to="/courses" className="dashboard-panel p-6 hover:-translate-y-1"><BookOpen className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Training & Courses</h3><p className="mt-2 text-sm text-muted-foreground">Build practical skills through structured learning.</p></Link><Link to="/referrals" className="dashboard-panel p-6 hover:-translate-y-1"><Users className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Networking</h3><p className="mt-2 text-sm text-muted-foreground">Connect with your community and grow your team.</p></Link><Link to="/rewards" className="dashboard-panel p-6 hover:-translate-y-1"><Crown className="size-8 text-primary" /><h3 className="mt-4 text-xl font-bold">Ranks & Rewards</h3><p className="mt-2 text-sm text-muted-foreground">Track your progress and achievement rewards.</p></Link></div></section>
    <section className="mx-5 mb-16 rounded-3xl bg-foreground px-6 py-12 text-center text-background lg:mx-auto lg:max-w-7xl"><h2 className="text-3xl font-black">Your journey starts now.</h2><Link to="/login" className="mt-6 inline-flex"><Button className="bg-primary text-primary-foreground">Get started <ArrowRight className="ml-2 size-4" /></Button></Link></section><footer className="border-t border-border px-5 py-8 text-center text-sm text-muted-foreground">© {new Date().getFullYear()} {BRAND_NAME}. Learn • Earn • Grow.</footer>
  </div>;
}
