/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RReferralCodeRouteImport } from './routes/r.$referralCode'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppReferralsRouteImport } from './routes/_app/referrals'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppLuckyDrawRouteImport } from './routes/_app/lucky-draw'
import { Route as AppJoinRouteImport } from './routes/_app/join'
import { Route as AppEarningsRouteImport } from './routes/_app/earnings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RReferralCodeRoute = RReferralCodeRouteImport.update({
  id: '/r/$referralCode',
  path: '/r/$referralCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppLuckyDrawRoute = AppLuckyDrawRouteImport.update({
  id: '/lucky-draw',
  path: '/lucky-draw',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/earnings': typeof AppEarningsRoute
  '/join': typeof AppJoinRoute
  '/lucky-draw': typeof AppLuckyDrawRoute
  '/plans': typeof AppPlansRoute
  '/referrals': typeof AppReferralsRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/r/$referralCode': typeof RReferralCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/earnings': typeof AppEarningsRoute
  '/join': typeof AppJoinRoute
  '/lucky-draw': typeof AppLuckyDrawRoute
  '/plans': typeof AppPlansRoute
  '/referrals': typeof AppReferralsRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/wallet': typeof AppWalletRoute
  '/r/$referralCode': typeof RReferralCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/earnings': typeof AppEarningsRoute
  '/_app/join': typeof AppJoinRoute
  '/_app/lucky-draw': typeof AppLuckyDrawRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/r/$referralCode': typeof RReferralCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/earnings'
    | '/join'
    | '/lucky-draw'
    | '/plans'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/wallet'
    | '/r/$referralCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/earnings'
    | '/join'
    | '/lucky-draw'
    | '/plans'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/wallet'
    | '/r/$referralCode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/earnings'
    | '/_app/join'
    | '/_app/lucky-draw'
    | '/_app/plans'
    | '/_app/referrals'
    | '/_app/rewards'
    | '/_app/settings'
    | '/_app/wallet'
    | '/r/$referralCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RReferralCodeRoute: typeof RReferralCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$referralCode': {
      id: '/r/$referralCode'
      path: '/r/$referralCode'
      fullPath: '/r/$referralCode'
      preLoaderRoute: typeof RReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lucky-draw': {
      id: '/_app/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/lucky-draw'
      preLoaderRoute: typeof AppLuckyDrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join': {
      id: '/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earnings': {
      id: '/_app/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppJoinRoute: typeof AppJoinRoute
  AppLuckyDrawRoute: typeof AppLuckyDrawRoute
  AppPlansRoute: typeof AppPlansRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppJoinRoute: AppJoinRoute,
  AppLuckyDrawRoute: AppLuckyDrawRoute,
  AppPlansRoute: AppPlansRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoursesRoute: CoursesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RReferralCodeRoute: RReferralCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
